acsign/urls.py
from django.urls import path

from . import views

#namespace
app_name = 'acsign'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:activity_id>/', views.detail, name='detail'),
    path('<int:activity_id>/results/', views.results, name='results'),
    path('<int:activity_id>/sign/', views.sign, name='sign'),
]

sign/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('acsign/', include('acsign.urls')),
    path('admin/', admin.site.urls),
]

acsign/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Activity(models.Model):
    activity_theme = models.CharField(max_length=200)
    activity_creator = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.activity_theme
    def was_published_recently(self):
        return self.pub_date >= timezone.now()
    datetime.timedelta(days=1)

class Sign(models.Model):
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE)
    sign_name = models.CharField(max_length=200)
    sign_date = models.DateTimeField('date sign')
    def __str__(self):
        return self.sign_name

acsign/views.py
from django.shortcuts import get_object_or_404, render
from django.http import Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.utils import timezone
from django.urls import reverse
from .models import Sign, Activity

# Create your views here.
def index(request):
    latest_activity_list = Activity.objects.order_by('pub_date')[:2]
    template = loader.get_template('acsign/index.html')
    context = {'latest_activity_list':latest_activity_list,}
    return HttpResponse(template.render(context, request))

def detail(request, activity_id):
    try:
        activity = Activity.objects.get(pk=activity_id)
    except Activity.DoesNotExist:
        raise Http404("Activity does not exit")
    return render(request, 'acsign/detail.html', {'activity':activity})

def results(request, activity_id):
    activity = get_object_or_404(Activity, pk=activity_id)
    return render(request, 'acsign/results.html', {'activity':activity})

def sign(request, activity_id):
    activity = get_object_or_404(Activity, pk=activity_id)
    sign_name = request.POST['sign_name']

    #防止重复签到
    for sign_object in activity.sign_set.all():
        if sign_name == sign_object.sign_name:
            return render(request, 'acsign/detail.html', {
                'activity': activity,
                'error_message': "You have signed, don't repeat sign.",
            })
    #防止签到数据为空
    if "" == sign_name or "InputYourName" == sign_name :
        return render(request, 'acsign/detail.html', {
            'activity': activity,
            'error_message': "You didn't sign by your name.",
        })
    else:
        activity.sign_set.create(sign_name=sign_name, sign_date=timezone.now())
        activity.save()

    #返回签到成功后页面，即调用results函数
    return HttpResponseRedirect(reverse('acsign:results', args=(activity_id,)))

acsign/templates/acsign/detail.html
<h1>{{activity.activity_theme}}</h1>
<h3>{{activity.pub_date}}</h3>

{% if error_message %}<p><strong>{{error_message}}</strong></p>
{% endif %}

<form action="{% url 'acsign:sign' activity.id %}" method="post">
    {% csrf_token %}
    sign_name: <input type="text" name="sign_name" value="InputYourName"><br>
    <input type="submit" value="签到">
    <ul>
    {% for sign in activity.sign_set.all %}
        <li>{{ sign.sign_name }} -- {{ sign.sign_date }}</li>
    {% endfor %}
    </ul>
</form>

acsign/templates/acsign/index.html
{% if latest_activity_list %}
    <ul>
        {% for activity in latest_activity_list %}
            <li><a href="{% url 'acsign:detail' activity.id %}">
                {{activity.activity_theme}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No activity are available.</p>
{% endif %}

acsign/templates/acsign/results.html
<h1>{{activity.activity_theme}}</h1>
<h3>{{activity.pub_date}}</h3>

<ul>
    {% for sign in activity.sign_set.all %}
        <li>{{ sign.sign_name }} -- {{ sign.sign_date }}</li>
    {% endfor %}
</ul>
<a href="{% url 'acsign:detail' activity.id %}">Sign again</a>